config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :ro_packages, :controller => :ro_packages

resources :ro_testcases, :controller => :ro_testcases

app/models/ro_package.rb
class RoPackage < ActiveRecord::Base
  # 1: active, 2: closed
  enum status: { active: 1, closed: 2 }
end

app/models/ro_package_tag.rb
class RoPackageTag < ActiveRecord::Base
end

app/models/ro_ptag.rb
class RoPtag < ActiveRecord::Base
end

app/models/ro_test_step.rb
class RoTestStep < ActiveRecord::Base
end

app/models/ro_testcase.rb
class RoTestcase < ActiveRecord::Base
end

app/models/ro_testcase_tag.rb
class RoTestcaseTag < ActiveRecord::Base
end

app/models/ro_ttag.rb
class RoTtag < ActiveRecord::Base
end

app/controllers/ro_package_tags_controller.rb
class RoPackageTagsController < ApplicationController
end

app/controllers/ro_packages_controller.rb
class RoPackagesController < ApplicationController
  layout "osp"
  before_action :set_package, only: [:edit, :update, :show, :destroy]

  def index
    @packages = RoPackage.where(status: :active).order(:package_name)
  end

  def new
    @package = RoPackage.new
  end

  def create
    RoPackage.create package_params

    redirect_to ro_packages_path
  end

  def edit
    #
  end

  def update
    @package.update(package_params)

    redirect_to ro_packages_path
  end

  def show
    #
  end

  private

  def package_params
    params.require(:ro_package).permit(:package_name, :description)
  end

  def set_package
    @package = RoPackage.find(params[:id])
  end
end

app/controllers/ro_test_case_tags_controller.rb
class RoTestCaseTagsController < ApplicationController
end

app/controllers/ro_test_steps_controller.rb
class RoTestStepsController < ApplicationController
end

app/controllers/ro_testcases_controller.rb
class RoTestcasesController < ApplicationController
  layout "osp"
  before_action :set_testcase, only: [:edit, :update, :show, :destroy]

  def index
    @testcases = RoTestcase.all
  end

  def new
    @testcase = RoTestcase.new
  end

  def create
    RoTestcase.create(testcase_params)
  end

  def edit
    #
  end

  def update
    #
  end

  def show
    #
  end

  private

  def testcase_params
    params.require(:ro_testcase).permit(:testcase_name, :precondition, :postaction, :status, :package_id)
  end

  def set_testcase
    @testcase = RoTestcase.find(params[:id])
  end
end

app/helpers/ro_package_tags_helper.rb
module RoPackageTagsHelper
end

app/helpers/ro_packages_helper.rb
module RoPackagesHelper
end

app/helpers/ro_test_case_tags_helper.rb
module RoTestCaseTagsHelper
end

app/helpers/ro_test_cases_helper.rb
module RoTestCasesHelper
end

app/helpers/ro_test_steps_helper.rb
module RoTestStepsHelper
end

app/views/layouts/osp.html.erb
<!DOCTYPE html>
<html lang="<%= current_language %>">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <title><%= html_title %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta name="description" content="<%= Redmine::Info.app_name %>" />
  <meta name="keywords" content="issue,bug,tracker" />
  <%= csrf_meta_tag %>
  <%= favicon %>
  <%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
  <%= stylesheet_link_tag 'bootstrap.min.css', 'custom.css', :plugin => 'redmine_osp', :media => 'all' %>
  <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
  <%= javascript_heads %>
  <%= heads_for_theme %>
  <%= call_hook :view_layouts_base_html_head %>
  <!-- page specific tags -->
  <%= yield :header_tags -%>
  <%= javascript_include_tag 'bootstrap.min', :plugin => 'redmine_osp' %>
</head>
<body class="<%= body_css_classes %>">
<%= call_hook :view_layouts_base_body_top %>
<div id="wrapper">

  <div class="flyout-menu js-flyout-menu">


    <% if User.current.logged? || !Setting.login_required? %>
        <div class="flyout-menu__search">
          <%= form_tag({:controller => 'search', :action => 'index', :id => @project}, :method => :get ) do %>
              <%= hidden_field_tag(controller.default_search_scope, 1, :id => nil) if controller.default_search_scope %>
              <%= label_tag 'flyout-search', '&#9906;'.html_safe, :class => 'search-magnifier search-magnifier--flyout' %>
              <%= text_field_tag 'q', @question, :id => 'flyout-search', :class => 'small js-search-input', :placeholder => l(:label_search) %>
          <% end %>
        </div>
    <% end %>

    <% if User.current.logged? %>
        <div class="flyout-menu__avatar <% if !Setting.gravatar_enabled? %>flyout-menu__avatar--no-avatar<% end %>">
          <% if Setting.gravatar_enabled? %>
              <%= link_to(avatar(User.current, :size => "80"), user_path(User.current)) %>
          <% end %>
          <%= link_to_user(User.current, :format => :username) %>
        </div>
    <% end %>

    <% if display_main_menu?(@project) %>
        <h3><%= l(:label_project) %></h3>
        <span class="js-project-menu"></span>
    <% end %>

    <h3><%= l(:label_general) %></h3>
    <span class="js-general-menu"></span>

    <span class="js-sidebar flyout-menu__sidebar"></span>

    <h3><%= l(:label_profile) %></h3>
    <span class="js-profile-menu"></span>

  </div>

  <div id="wrapper2">
    <div id="wrapper3">
      <div id="top-menu">
        <div id="account">
          <%= render_menu :account_menu -%>
        </div>
        <%= content_tag('div', "#{l(:label_logged_as)} #{link_to_user(User.current, :format => :username)}".html_safe, :id => 'loggedas') if User.current.logged? %>
        <%= render_menu :top_menu if User.current.logged? || !Setting.login_required? -%>
      </div>

      <div id="header">

        <a href="#" class="mobile-toggle-button js-flyout-menu-toggle-button"></a>

        <% if User.current.logged? || !Setting.login_required? %>
            <div id="quick-search">
              <%= form_tag({:controller => 'search', :action => 'index', :id => @project}, :method => :get ) do %>
                  <%= hidden_field_tag 'scope', default_search_project_scope, :id => nil %>
                  <%= hidden_field_tag(controller.default_search_scope, 1, :id => nil) if controller.default_search_scope %>
                  <label for='q'>
                    <%= link_to l(:label_search), {:controller => 'search', :action => 'index', :id => @project}, :accesskey => accesskey(:search) %>:
                  </label>
                  <%= text_field_tag 'q', @question, :size => 20, :class => 'small', :accesskey => accesskey(:quick_search) %>
              <% end %>
              <%= render_project_jump_box %>
            </div>
        <% end %>

        <h1><%= page_header_title %></h1>

        <% if display_main_menu?(@project) %>
            <div id="main-menu" class="tabs">
              <%= render_main_menu(@project) %>
              <div class="tabs-buttons" style="display:none;">
                <button class="tab-left" onclick="moveTabLeft(this); return false;"></button>
                <button class="tab-right" onclick="moveTabRight(this); return false;"></button>
              </div>
            </div>
        <% end %>
      </div>

      <div id="main" class="<%= sidebar_content? ? '' : 'nosidebar' %>">
        <div id="sidebar">
          <%= yield :sidebar %>
          <%= view_layouts_base_sidebar_hook_response %>
        </div>

        <div id="content" class="ospPlugin">
          <%= render_flash_messages %>
          <%= render partial: 'ro_share/tab' %>
          <%= yield %>
          <%= call_hook :view_layouts_base_content %>
          <div style="clear:both;"></div>
        </div>
      </div>
    </div>

    <div id="ajax-indicator" style="display:none;"><span><%= l(:label_loading) %></span></div>
    <div id="ajax-modal" style="display:none;"></div>

    <div id="footer">
      <div class="bgl"><div class="bgr">
        Powered by <%= link_to Redmine::Info.app_name, Redmine::Info.url %> &copy; 2006-2018 Jean-Philippe Lang
      </div></div>
    </div>
  </div>
</div>
<%= call_hook :view_layouts_base_body_bottom %>
</body>
</html>

app/views/ro_packages/_form.html.erb
<%= form_with model: @package do |form| %>
    <div class="box tabular">
      <p>
        <label>Name:</label>
        <%= form.text_field :package_name %>
      </p>
      <p>
        <label>Description</label>
        <%= form.text_area :description, rows: 5, cols: 5 %>
      </p>
    </div>
    <%= form.submit %>
<% end %>

app/views/ro_packages/edit.html.erb
<%= render 'form' %>

app/views/ro_packages/index.html.erb
<div class="contextual">
  <%= link_to t('ro.lbl_package_new'), new_ro_package_path, :class => 'icon icon-add new-issue' %>
</div>
<h2>Packages</h2>

<div class="autoscroll">
  <table class="list issues odd-even">
    <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>Tags</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @packages.each do |p| %>
        <tr>
          <td><%= link_to p.id, ro_package_path(p.id) %></td>
          <td><%= link_to p.package_name, ro_package_path(p.id) %></td>
          <td><%= p.description %></td>
          <td></td>
          <td>
            <%= link_to 'Edit', edit_ro_package_path(p.id) %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/ro_packages/new.html.erb
<%= render 'form' %>

app/views/ro_packages/show.html.erb
<form class="form-horizontal">
  <div class="form-group">
    <label class="col-sm-2 control-label">Package Name</label>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @package.package_name %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Description</label>
    <div class="col-sm-10">
      <p class="form-control-static"><%= @package.description %></p>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-2 control-label">Test Cases</label>
    <div class="col-sm-10">
      <div class="panel panel-default">
        <div class="panel-heading">
          <label class="btn btn-success btn-xs" data-toggle="modal" data-target="#addTestCase">Add Test Case</label>
        </div>
        <div class="panel-body">
          <table class="table table-striped">
            <thead>
            <tr>
              <th>Name</th>
              <th>Description</th>
              <th>Status</th>
            </tr>
            </thead>
            <tbody>
            <tr>
              <td>TestCase1</td>
              <td>Des1</td>
              <td><span class="label label-success">Active</span></td>
            </tr>
            <tr>
              <td>TestCase1</td>
              <td>Des1</td>
              <td><span class="label label-default">Waiting</span></td>
            </tr>
            <tr>
              <td>TestCase1</td>
              <td>Des1</td>
              <td><span class="label label-default">Waiting</span></td>
            </tr>
            <tr>
              <td>TestCase1</td>
              <td>Des1</td>
              <td><span class="label label-success">Active</span></td>
            </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</form>

<!-- Modal -->
<div class="modal fade" id="addTestCase" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/ro_share/_tab.html.erb
<div class="tabs">
  <ul>
    <li><%= link_to t('ro.packages'), ro_packages_path %></li>
    <li><%= link_to t('ro.testcases'), ro_testcases_path %></li>
  </ul>
</div>

app/views/ro_testcases/_form.html.erb
<%= form_with model: @testcase do |form| %>
    <div class="box tabular">
      <p>
        <label>Name:</label>
        <%= form.text_field :testcase_name %>
      </p>
      <p>
        <label>Precondition</label>
        <%= form.text_area :description, rows: 5, cols: 5 %>
      </p>
      <p>
        <label>Postaction</label>
        <%= form.text_field :postaction %>
      </p>
      <p>
        <fieldset>
          <legend>Steps:</legend>
          <div class="w3-row">
            <div class="w3-quarte">
              <label>Name</label>
              <%= form.text_field :command %>
            </div>

            <div class="w3-quarte">
              <label>Exactly</label>
              <%= form.check_box :exactly %>
            </div>

            <div class="w3-quarte">
              <label>Expected Output</label>
              <%= form.text_field :expected_output %>
            </div>
            <span class="icon icon-plus"></span>
          </div>
        </fieldset>
      </p>
    </div>
    <%= form.submit %>
<% end %>

app/views/ro_testcases/index.html.erb
<h2>TestCase</h2>

<div class="autoscroll">
  <table class="list issues odd-even">
    <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Description</th>
      <th>Tags</th>
      <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <% @testcases.each do |p| %>
        <tr>
          <td><%= p.id %></td>
          <td><%= p.precondition %></td>
          <td><%= p.postaction %></td>
          <td></td>
          <td>

          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/ro_testcases/new.html.erb
<%= render 'form' %>